### ISSUE TITLE
Is possible to have a c++ wrapper

### ISSUE THREAD

**Issue by mingodad** [msharov/casycom#1]
Hello !
I've been reading the documentation and there is a lot of boilerplate to use this library.
Is it possible to provide a C++ wrapper that give a high level interface to use it ?
You already did a great job with ustl, a high level interface to this library using ustl will make the entry level usage a lot easier.

Something Like:
```
class Casycom
{
protected:
    Interface *methodes;
    string name;
public:
    Casycom(){...}
    virtual ~Casycom(){...}
    void getExportedMethods();
    virtual void onmessage(const Msg* msg);
    void sendmessage(const Msg* msg);
}
```
Then the users of this library only need to derive a class from it and fill the blanks, no boilerplate for most common cases.

Cheers !

**Comment by msharov** [comment]
casycom is a pure C library implementation of this particular COM protocol. I already have a c++ version, which I have no plans to open source. You can look at my GLERI project for another C++ implementation of this COM protocol.

**Comment by mingodad** [comment]
I cloned https://github.com/msharov/gleri and searched by casycom and found
nothing !
Are you sure ?

**Comment by msharov** [comment]
GLERI does not currently use casycom. I mention it because it has the C++ implementation of the same COM system.
